# Generated by Django 6.0.6 on 2026-06-14 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_remove_job_profile_picture_job_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_picture',
            field=models.ImageField(blank=True, null=True, upload_to='jobs/'),
        ),
    ]
